apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: prod
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: py-app
        image: 1aughingbird543/py-app:1.3.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-data
              key: PASSWORD
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-data
              key: USER
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-data
              key: NAME
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: configmap 
              key: ENV
        ports:
        - containerPort: 80
