apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: py-app=1aughingbird543/py-app
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
    argocd-image-updater.argoproj.io/nginx.ignore-tags: latest
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: https://github.com/Slava-png/argo-practice
    targetRevision: HEAD
    path: ./env/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true