apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Slava-png/argo-practice
    targetRevision: HEAD
    path: ./env/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true